services:
  app:
    container_name: meshqu-backend-app
    build:
      context: .
    restart: always
    volumes:
      - meshque-static-data:/vol/web
    env_file:
      - .env.production

volumes:
  meshque-static-data:
